# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/HSLTalks',
                'doc_host': 'https://ninjalabo.github.io',
                'git_url': 'https://github.com/ninjalabo/HSLTalks',
                'lib_path': 'HSLTalks'},
  'syms': {'HSLTalks.core': {'HSLTalks.core.foo': ('core.html#foo', 'HSLTalks/core.py')}}}
